-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 11:59:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zub` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `zub` ;

-- -----------------------------------------------------
-- Table `zub`.`staff_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`staff_access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(255) NOT NULL,
  `date_birth` DATE NOT NULL,
  `passport` VARCHAR(255) NULL DEFAULT NULL,
  `bank_details` VARCHAR(255) NULL DEFAULT NULL,
  `staff_access_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_staff_access1_idx` (`staff_access_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_staff_access1`
    FOREIGN KEY (`staff_access_id`)
    REFERENCES `zub`.`staff_access` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`managers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(255) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_managers_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_managers_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `zub`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`partners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_company` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `inn` INT NOT NULL,
  `fio_owner` VARCHAR(255) NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `points_sale` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`applications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `managers_id` INT NOT NULL,
  `partners_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applications_managers1_idx` (`managers_id` ASC) VISIBLE,
  INDEX `fk_applications_partners1_idx` (`partners_id` ASC) VISIBLE,
  CONSTRAINT `fk_applications_managers1`
    FOREIGN KEY (`managers_id`)
    REFERENCES `zub`.`managers` (`id`),
  CONSTRAINT `fk_applications_partners1`
    FOREIGN KEY (`partners_id`)
    REFERENCES `zub`.`partners` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `inn` BIGINT NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  `date_start_supplier` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`materials` (
  `id` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `price` VARCHAR(255) NOT NULL,
  `unit_pack` INT NOT NULL,
  `unit_warehouse` INT NOT NULL,
  `unit_min` INT NOT NULL,
  `history` TEXT NULL DEFAULT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materials_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_materials_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `zub`.`suppliers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `article` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price_min_partner` INT NULL DEFAULT NULL,
  `size` VARCHAR(255) NOT NULL,
  `number_standard` INT NULL DEFAULT NULL,
  `history_price_min_partner` TEXT NULL DEFAULT NULL,
  `date_create` DATE NOT NULL,
  `cost` INT NOT NULL,
  `materials_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_materials1_idx` (`materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `zub`.`materials` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zub`.`warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zub`.`warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` TEXT NOT NULL,
  `entrance` INT NULL DEFAULT NULL,
  `disposal` INT NULL DEFAULT NULL,
  `materials_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_warehouses_materials1_idx` (`materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_warehouses_materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `zub`.`materials` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
